dotnet "D:\GitHub\guitarrapc\CsProjEditor\console\dotnet-csproj\bin\Debug\netcoreapp2.1\publish\dotnet-csproj.dll" NodeValue.Set -p "C:\Users\admin\Downloads\uwp\test.csproj" -g PropertyGroup -n PackageCertificateKeyFile -v hogehoge.pfx -dry false -output "C:\Users\admin\Downloads\uwp\result.csproj" -allowoverwrite true
dotnet "D:\GitHub\guitarrapc\CsProjEditor\console\dotnet-csproj\bin\Debug\netcoreapp2.1\publish\dotnet-csproj.dll" Node.Insert -p "C:\Users\admin\Downloads\uwp\result.csproj" -g PropertyGroup -n PackageCertificateThumbprint -v 1234567890ABCDEF -dry false -output "C:\Users\admin\Downloads\uwp\result.csproj" -allowoverwrite true
dotnet "D:\GitHub\guitarrapc\CsProjEditor\console\dotnet-csproj\bin\Debug\netcoreapp2.1\publish\dotnet-csproj.dll" Node.Insert -p "C:\Users\admin\Downloads\uwp\result.csproj" -g PropertyGroup -n GenerateAppInstallerFile -v False -dry false -output "C:\Users\admin\Downloads\uwp\result.csproj" -allowoverwrite true
dotnet "D:\GitHub\guitarrapc\CsProjEditor\console\dotnet-csproj\bin\Debug\netcoreapp2.1\publish\dotnet-csproj.dll" Node.Insert -p "C:\Users\admin\Downloads\uwp\result.csproj" -g PropertyGroup -n AppxAutoIncrementPackageRevision -v True -dry false -output "C:\Users\admin\Downloads\uwp\result.csproj" -allowoverwrite true
dotnet "D:\GitHub\guitarrapc\CsProjEditor\console\dotnet-csproj\bin\Debug\netcoreapp2.1\publish\dotnet-csproj.dll" Node.Insert -p "C:\Users\admin\Downloads\uwp\result.csproj" -g PropertyGroup -n AppxSymbolPackageEnabled -v False -dry false -output "C:\Users\admin\Downloads\uwp\result.csproj" -allowoverwrite true
dotnet "D:\GitHub\guitarrapc\CsProjEditor\console\dotnet-csproj\bin\Debug\netcoreapp2.1\publish\dotnet-csproj.dll" Node.Insert -p "C:\Users\admin\Downloads\uwp\result.csproj" -g PropertyGroup -n AppxBundle -v Always -dry false -output "C:\Users\admin\Downloads\uwp\result.csproj" -allowoverwrite true
dotnet "D:\GitHub\guitarrapc\CsProjEditor\console\dotnet-csproj\bin\Debug\netcoreapp2.1\publish\dotnet-csproj.dll" Node.Insert -p "C:\Users\admin\Downloads\uwp\result.csproj" -g PropertyGroup -n AppxBundlePlatforms -v x86 -dry false -output "C:\Users\admin\Downloads\uwp\result.csproj" -allowoverwrite true
dotnet "D:\GitHub\guitarrapc\CsProjEditor\console\dotnet-csproj\bin\Debug\netcoreapp2.1\publish\dotnet-csproj.dll" Node.Insert -p "C:\Users\admin\Downloads\uwp\result.csproj" -g PropertyGroup -n AppInstallerUpdateFrequency -v 1 -dry false -output "C:\Users\admin\Downloads\uwp\result.csproj" -allowoverwrite true
dotnet "D:\GitHub\guitarrapc\CsProjEditor\console\dotnet-csproj\bin\Debug\netcoreapp2.1\publish\dotnet-csproj.dll" Node.Insert -p "C:\Users\admin\Downloads\uwp\result.csproj" -g PropertyGroup -n AppInstallerCheckForUpdateFrequency -v OnApplicationRun -dry false -output "C:\Users\admin\Downloads\uwp\result.csproj" -allowoverwrite true
dotnet "D:\GitHub\guitarrapc\CsProjEditor\console\dotnet-csproj\bin\Debug\netcoreapp2.1\publish\dotnet-csproj.dll" Node.Insert -p "C:\Users\admin\Downloads\uwp\result.csproj" -g PropertyGroup -n AppxSymbolPackageEnabled -v False -dry false -output "C:\Users\admin\Downloads\uwp\result.csproj" -allowoverwrite true
dotnet "D:\GitHub\guitarrapc\CsProjEditor\console\dotnet-csproj\bin\Debug\netcoreapp2.1\publish\dotnet-csproj.dll" Attribute.Insert -p "C:\Users\admin\Downloads\uwp\result.csproj" -g ItemGroup -n None -a Include -v hogehoge.pfx -dry false -output "C:\Users\admin\Downloads\uwp\result.csproj" -allowoverwrite true
dotnet "D:\GitHub\guitarrapc\CsProjEditor\console\dotnet-csproj\bin\Debug\netcoreapp2.1\publish\dotnet-csproj.dll" Attribute.Insert -p "C:\Users\admin\Downloads\uwp\result.csproj" -g ItemGroup -n None -a Include -v Package.StoreAssociation.xml -dry false -output "C:\Users\admin\Downloads\uwp\result.csproj" -allowoverwrite true

